#!/usr/bin/env bash


# Use imagemagick conversion to convert image. 

function help {
        if [ -n "${1}" ]; then
              echo "${1}"
        fi
        cat <<-EOF

        Usage: resize [filename] [value in percent without % symbol] 

        Downsize image in percentage of original image. Output filename
        will in format of resized[percentage]_[originalfilename].

                -h      - print help and exit

EOF

        if [ -n "${1}" ]; then
                exit 1
        fi
        exit 0
}

 if [ "${1}" == '-h' ]; then
         help
 elif [ "${1:0:1}" == '' ]; then
         echo "Error: unknown option $1. Try \"-h\" "
         exit 0
 fi
 # Check if imagemagick is install
 if [ ! "$(command -v magick)" ]; then
            echo "Could not find Imagemagick. Kindly install from your package manager"
        exit 1
 fi
# Check file type
identify $1 &> /dev/null
filetype=$(echo $?)
if [ $filetype = 1 ]; then
        echo "Error - Unknown filetype or bad filename. Try \"-h\" "
        exit 1
else
        #Converting the image
        magick convert -resize $2% $1 resized$2_$1
fi


